/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package group8;

//import javax.swing.JOptionPane;

public class MAIN_INTERFACE extends javax.swing.JApplet {

    //Globals
    public InventoryList inventoryList;

    public void InitializeView() {
        inventoryList = new InventoryList(); //Model
        
        jInventoryList.setModel(new javax.swing.AbstractListModel() {
        public int getSize() { 
            return inventoryList.getSize(); 
        }
        public Object getElementAt(int i) { 
            return inventoryList.getItemAtIndex(i).getItemName();
        }
        });

    }
    
    public void DisableItemFields() {
        jItemNameTF.setEditable(false);
        jItemIdTF.setEditable(false);
        jItemSellPriceTF.setEditable(false);
        jItemStockPriceTF.setEditable(false);
        jItemCountTF.setEditable(false);
        jItemWeightTF.setEditable(false);
        
        jRemoveItemButton.setEnabled(false);
        jAddItemButton.setEnabled(false);
    }
    
    public void EnableItemFields() {
        jItemNameTF.setEditable(true);
        jItemIdTF.setEditable(true);
        jItemSellPriceTF.setEditable(true);
        jItemStockPriceTF.setEditable(true);
        //jItemCountTF.setEditable(false);
        jItemWeightTF.setEditable(true);
        
        jRemoveItemButton.setEnabled(true);
        jAddItemButton.setEnabled(true);
    }
    
    public void usingItemEditor() {
        this.EnableItemFields();
        jUpdateAddButton.setEnabled(true);
        jCancelButton.setEnabled(true);
        jEditButton.setEnabled(false);
        jNewItemButton.setEnabled(false);
        jInventoryList.setEnabled(false);
    }
    
    public void notUsingItemEditor() {
        jCancelButton.setEnabled(false);
        jUpdateAddButton.setEnabled(false);
        jEditButton.setEnabled(true);
        jNewItemButton.setEnabled(true);
        this.DisableItemFields();
        jInventoryList.setEnabled(true);
    }
    
    public void handelItemUpdate() {
        int selectedIndex = jInventoryList.getSelectedIndex();
        System.out.print(Integer.toString(selectedIndex));
        Item item = inventoryList.getItemAtIndex(selectedIndex);
        item.itemName = jItemNameTF.getText();
        //no need to reloadTableView
    }
    
    //@Override
    public void init() {
        this.setSize(800, 700);
        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        InitializeView();
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInventoryListPane = new javax.swing.JScrollPane();
        jInventoryList = new javax.swing.JList();
        jShippedPane = new javax.swing.JScrollPane();
        jShippedList = new javax.swing.JList();
        jToShipPane = new javax.swing.JScrollPane();
        jToShipList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jItemNameTF = new javax.swing.JTextField();
        jRemoveItemButton = new javax.swing.JButton();
        jAddItemButton = new javax.swing.JButton();
        jItemIdTF = new javax.swing.JTextField();
        jItemSellPriceTF = new javax.swing.JTextField();
        jItemStockPriceTF = new javax.swing.JTextField();
        jItemCountTF = new javax.swing.JTextField();
        jItemWeightTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jEditButton = new javax.swing.JButton();
        jUpdateAddButton = new javax.swing.JButton();
        jNewItemButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(null);

        jInventoryList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInventoryList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jInventoryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jInventoryListValueChanged(evt);
            }
        });
        jInventoryListPane.setViewportView(jInventoryList);

        getContentPane().add(jInventoryListPane);
        jInventoryListPane.setBounds(10, 50, 120, 330);

        jShippedList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jShippedList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jShippedPane.setViewportView(jShippedList);

        getContentPane().add(jShippedPane);
        jShippedPane.setBounds(270, 50, 120, 330);

        jToShipList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToShipList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jToShipPane.setViewportView(jToShipList);

        getContentPane().add(jToShipPane);
        jToShipPane.setBounds(140, 50, 120, 330);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shipped");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 20, 80, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Invetory");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 80, 30);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("To Ship");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 20, 80, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel4.setText("Weight:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 170, 70, 16);

        jLabel5.setText("Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 20, 40, 16);

        jLabel6.setText("Id:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 50, 45, 16);

        jLabel7.setText("SellPrice:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 80, 60, 16);

        jLabel8.setText("StockPrice:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 110, 70, 16);

        jLabel9.setText("Count:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 140, 70, 16);

        jItemNameTF.setEditable(false);
        jPanel1.add(jItemNameTF);
        jItemNameTF.setBounds(110, 20, 200, 20);

        jRemoveItemButton.setText("<");
        jPanel1.add(jRemoveItemButton);
        jRemoveItemButton.setBounds(210, 140, 20, 20);

        jAddItemButton.setText(">");
        jPanel1.add(jAddItemButton);
        jAddItemButton.setBounds(230, 140, 20, 20);

        jItemIdTF.setEditable(false);
        jPanel1.add(jItemIdTF);
        jItemIdTF.setBounds(110, 50, 200, 20);

        jItemSellPriceTF.setEditable(false);
        jPanel1.add(jItemSellPriceTF);
        jItemSellPriceTF.setBounds(110, 80, 100, 20);

        jItemStockPriceTF.setEditable(false);
        jPanel1.add(jItemStockPriceTF);
        jItemStockPriceTF.setBounds(110, 110, 100, 20);

        jItemCountTF.setEditable(false);
        jPanel1.add(jItemCountTF);
        jItemCountTF.setBounds(110, 140, 100, 20);

        jItemWeightTF.setEditable(false);
        jPanel1.add(jItemWeightTF);
        jItemWeightTF.setBounds(110, 170, 100, 20);

        jLabel15.setText("$");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(210, 83, 20, 16);

        jLabel16.setText("$");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(210, 113, 20, 16);

        jLabel17.setText("kg");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(210, 173, 20, 16);

        jEditButton.setText("Edit Item");
        jEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jEditButton);
        jEditButton.setBounds(10, 220, 140, 29);

        jUpdateAddButton.setText("Add/Update Item");
        jUpdateAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateAddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jUpdateAddButton);
        jUpdateAddButton.setBounds(170, 220, 140, 29);

        jNewItemButton.setText("New Item");
        jPanel1.add(jNewItemButton);
        jNewItemButton.setBounds(10, 250, 140, 29);

        jCancelButton.setText("Cancel");
        jPanel1.add(jCancelButton);
        jCancelButton.setBounds(170, 250, 140, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(410, 240, 320, 290);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel12.setText("Total Revenue:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 20, 130, 20);

        jLabel13.setText("InvetoryStockTotal:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 50, 150, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(410, 50, 220, 90);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel10.setText("Cost/Weight:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 10, 90, 20);

        jLabel11.setText("Cost To Ship All Items:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 50, 150, 20);

        jTextField4.setEditable(false);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(114, 10, 100, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(410, 150, 220, 80);

        jButton2.setText("Ship");
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 390, 75, 29);

        jButton1.setText("Sell");
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 390, 70, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void jInventoryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jInventoryListValueChanged
        // TODO add your handling code here:
        int selectedIndex = jInventoryList.getSelectedIndex();
        Item item = inventoryList.getItemAtIndex(selectedIndex);
        jItemNameTF.setText(item.getItemName());
        jItemIdTF.setText(Integer.toString(item.itemID));
        jItemSellPriceTF.setText(Float.toString(item.itemSellPrice));
        jItemStockPriceTF.setText(Float.toString(item.itemBuyPrice));
        jItemCountTF.setText(Integer.toString(item.itemCount));
        jItemWeightTF.setText(Float.toString(item.itemWeight));
    }//GEN-LAST:event_jInventoryListValueChanged

    private void jEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditButtonActionPerformed
        // TODO add your handling code here:
        this.usingItemEditor();
    }//GEN-LAST:event_jEditButtonActionPerformed

    private void jUpdateAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateAddButtonActionPerformed
        // TODO add your handling code here:
        System.out.print("Add/Update");
        this.notUsingItemEditor();
        this.handelItemUpdate();
    }//GEN-LAST:event_jUpdateAddButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddItemButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JButton jEditButton;
    private javax.swing.JList jInventoryList;
    private javax.swing.JScrollPane jInventoryListPane;
    private javax.swing.JTextField jItemCountTF;
    private javax.swing.JTextField jItemIdTF;
    private javax.swing.JTextField jItemNameTF;
    private javax.swing.JTextField jItemSellPriceTF;
    private javax.swing.JTextField jItemStockPriceTF;
    private javax.swing.JTextField jItemWeightTF;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private static javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jNewItemButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jRemoveItemButton;
    private javax.swing.JList jShippedList;
    private javax.swing.JScrollPane jShippedPane;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JList jToShipList;
    private javax.swing.JScrollPane jToShipPane;
    private javax.swing.JButton jUpdateAddButton;
    // End of variables declaration//GEN-END:variables
}
